version: '3.0'

networks:
  software:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
  db-data:        

services:
    postgredb:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: xxx
            POSTGRES_USER: xxx
            POSTGRES_PASSWORD: xxx
        volumes:
            - ./database/postgre/:/docker-entrypoint-initdb.d/
        networks:
            software:
                ipv4_address: 172.20.0.19
        ports:
            - 5432:5432
    redis:
        restart: on-failure   
        image: redis
        container_name: dev_lemoras_redis
        ports:
            - 6379:6379 
        expose:
            - 6379
        networks:
            software:
                ipv4_address: 172.20.0.18